
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { HemantXmt as SampleProjectHemantXmt } from "./Sample.Project.model"
// @ts-ignore 
import { BlogModule as SampleProjectBlogModule } from "./Sample.Project.model"
// @ts-ignore 
import { HarshXmcTraining as SampleProjectHarshXmcTraining } from "./Sample.Project.model"
// @ts-ignore 
import { Sample as SampleProjectSample } from "./Sample.Project.model"
// @ts-ignore 
import { PPatel as SampleProjectPPatel } from "./Sample.Project.model"
// @ts-ignore 
import { Services as SampleProjectServices } from "./Sample.Project.model"
// @ts-ignore 
import { Parthxmc as SampleProjectParthxmc } from "./Sample.Project.model"

export namespace HemantXmt.Banner {

    /**
    * Represents the template /sitecore/templates/Project/developers/Hemant-XMT/Banner/BannerComponent
    */
    export type BannerComponent =  {
        fields?: { 
            /**
            * Represents the Content field (056ec996-7ff5-473c-8cf4-87dc358dad41).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (2c34dece-27a0-405e-a5d8-3d1159640f85).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Hemant-XMT/Banner/BannerComponent
    */
    export type BannerComponentJson =  {
        
            /**
            * Represents the Content field (056ec996-7ff5-473c-8cf4-87dc358dad41).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (2c34dece-27a0-405e-a5d8-3d1159640f85).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/developers/Blog Module/Blog Detail
    */
    export type BlogDetail =  {
        fields?: { 
            /**
            * Represents the blogTitle field (466394b8-f89d-45f5-b30b-616eb019f50f).
            */
            blogTitle?: Field<string>;

            /**
            * Represents the cardImage field (04066216-c68d-4f8c-b4e0-eca1c9190b3d).
            */
            cardImage?: ImageField;

            /**
            * Represents the Content field (d715408d-939c-4770-abaf-dcd48b4b0c8f).
            */
            Content?: Field<string>;

            /**
            * Represents the isArchived field (df04a794-ae9b-4f89-88c5-182f797a53c3).
            */
            isArchived?: Field<boolean>;

            /**
            * Represents the isFeatured field (dff8498d-83cf-49ac-9f03-0fc8e3f0382d).
            */
            isFeatured?: Field<boolean>;

            /**
            * Represents the publishDate field (5c4c0186-a517-495b-bec1-ff84aabf0e2a).
            */
            publishDate?: Field<string>;

            /**
            * Represents the shortDescription field (f178d888-87a9-42e1-93f7-793f3c570a0a).
            */
            shortDescription?: Field<string>;

            /**
            * Represents the Title field (d84d7746-ec8f-4734-8ed2-694eaf0c2109).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Blog Module/Blog Detail
    */
    export type BlogDetailJson =  {
        
            /**
            * Represents the blogTitle field (466394b8-f89d-45f5-b30b-616eb019f50f).
            */
            blogTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the cardImage field (04066216-c68d-4f8c-b4e0-eca1c9190b3d).
            */
            cardImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Content field (d715408d-939c-4770-abaf-dcd48b4b0c8f).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the isArchived field (df04a794-ae9b-4f89-88c5-182f797a53c3).
            */
            isArchived?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the isFeatured field (dff8498d-83cf-49ac-9f03-0fc8e3f0382d).
            */
            isFeatured?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the publishDate field (5c4c0186-a517-495b-bec1-ff84aabf0e2a).
            */
            publishDate?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the shortDescription field (f178d888-87a9-42e1-93f7-793f3c570a0a).
            */
            shortDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (d84d7746-ec8f-4734-8ed2-694eaf0c2109).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HarshXmcTraining.Cards {

    /**
    * Represents the template /sitecore/templates/Project/developers/Harsh-Xmc-Training/Cards/Card
    */
    export type Card =  {
        fields?: { 
            /**
            * Represents the Image field (6584c198-f2eb-4fdd-8a10-70489826495c).
            */
            Image?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Harsh-Xmc-Training/Cards/Card
    */
    export type CardJson =  {
        
            /**
            * Represents the Image field (6584c198-f2eb-4fdd-8a10-70489826495c).
            */
            Image?: {
                jsonValue: ImageField
            };


    }
}
export namespace HarshXmcTraining.Demo {

    /**
    * Represents the template /sitecore/templates/Project/developers/Harsh-Xmc-Training/Demo/Demo
    */
    export type Demo =  {
        fields?: { 
            /**
            * Represents the Description field (30aee73c-ae6b-4834-b8e2-d8719c30a5a8).
            */
            Description?: Field<string>;

            /**
            * Represents the Link field (af2a3dee-b839-4ee4-b5cd-3186fc9ed7b4).
            */
            Link?: LinkField;

            /**
            * Represents the Title field (e4a2456e-2517-4455-b3ee-7962d268c7b4).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Harsh-Xmc-Training/Demo/Demo
    */
    export type DemoJson =  {
        
            /**
            * Represents the Description field (30aee73c-ae6b-4834-b8e2-d8719c30a5a8).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Link field (af2a3dee-b839-4ee4-b5cd-3186fc9ed7b4).
            */
            Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Title field (e4a2456e-2517-4455-b3ee-7962d268c7b4).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace HemantXmt.Demo {

    /**
    * Represents the template /sitecore/templates/Project/developers/Hemant-XMT/Demo/DemoComponent
    */
    export type DemoComponent =  {
        fields?: { 
            /**
            * Represents the Content field (c7ff0f72-e7d4-4295-87eb-28976c4ff326).
            */
            Content?: Field<string>;

            /**
            * Represents the Link field (97be8c94-5a4d-4ae4-9590-69b14fdf68eb).
            */
            Link?: LinkField;

            /**
            * Represents the Title field (531cae37-a82f-4815-973f-7597be0604d5).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Hemant-XMT/Demo/DemoComponent
    */
    export type DemoComponentJson =  {
        
            /**
            * Represents the Content field (c7ff0f72-e7d4-4295-87eb-28976c4ff326).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Link field (97be8c94-5a4d-4ae4-9590-69b14fdf68eb).
            */
            Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Title field (531cae37-a82f-4815-973f-7597be0604d5).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace BlogModule.Components.Header {

    /**
    * Represents the template /sitecore/templates/Project/developers/Blog Module/Components/Header/Header
    */
    export type Header =  {
        fields?: { 
            /**
            * Represents the Logo field (9f06e093-61d5-4960-a75a-c8a0c81e1110).
            */
            Logo?: ImageField;

            /**
            * Represents the Navigation field (8b2b7c5c-0253-4c1b-83fa-55f0cbd02cab).
            */
            Navigation?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Blog Module/Components/Header/Header
    */
    export type HeaderJson =  {
        
            /**
            * Represents the Logo field (9f06e093-61d5-4960-a75a-c8a0c81e1110).
            */
            Logo?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Navigation field (8b2b7c5c-0253-4c1b-83fa-55f0cbd02cab).
            */
            Navigation?: {
                jsonValue: Item
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Blog Module/Components/Header/Header Folder
    */
    export type HeaderFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Blog Module/Components/Header/Header Folder
    */
    export type HeaderFolderJson =  {
        

    }
}
export namespace Sample.Project.developers {

    /**
    * Represents the template /sitecore/templates/Project/developers/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/developers/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }
}
export namespace HarshXmcTraining.Cards {

    /**
    * Represents the template /sitecore/templates/Project/developers/Harsh-Xmc-Training/Cards/MainCard
    */
    export type MainCard =  {
        fields?: { 
            /**
            * Represents the MainCards field (a96acebe-ae81-49b1-aeae-d58181cda9be).
            */
            MainCards?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Harsh-Xmc-Training/Cards/MainCard
    */
    export type MainCardJson =  {
        
            /**
            * Represents the MainCards field (a96acebe-ae81-49b1-aeae-d58181cda9be).
            */
            MainCards?: {
                jsonValue: Item[]
            };


    }
}
export namespace PPatel {

    /**
    * Represents the template /sitecore/templates/Project/developers/PPatel/MyFirstComponent
    */
    export type MyFirstComponent =  {
        fields?: { 
            /**
            * Represents the Description field (4e3daeb9-9ebd-4238-bf12-00482f660956).
            */
            Description?: Field<string>;

            /**
            * Represents the Image field (8ecb29bf-a7e8-452f-a801-f8425e35f9ab).
            */
            Image?: ImageField;

            /**
            * Represents the Title field (0d088a99-e7f6-4ce5-a7b4-1f606b4410fb).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/PPatel/MyFirstComponent
    */
    export type MyFirstComponentJson =  {
        
            /**
            * Represents the Description field (4e3daeb9-9ebd-4238-bf12-00482f660956).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (8ecb29bf-a7e8-452f-a801-f8425e35f9ab).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Title field (0d088a99-e7f6-4ce5-a7b4-1f606b4410fb).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Sample.Project.developers {

    /**
    * Represents the template /sitecore/templates/Project/developers/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (016e2c81-f4a8-4636-99f7-d223ee801615).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (d49a40d3-b4f8-453d-b8a8-2d54dd55b44c).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (016e2c81-f4a8-4636-99f7-d223ee801615).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (d49a40d3-b4f8-453d-b8a8-2d54dd55b44c).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}
export namespace Services {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Services Cards
    */
    export type ServicesCards =  {
        fields?: { 
            /**
            * Represents the __Standard Werte field (93ca6686-d483-44cd-b445-e002e80de82e).
            */
            PromoIcon?: ImageField;

            /**
            * Represents the Bild 2 field (4b5e4643-fe58-431b-9d2b-0ee738aaaf1c).
            */
            PromoIcon2?: ImageField;

            /**
            * Represents the Link field (538c5149-6df9-46c1-84b7-02287a7a283a).
            */
            PromoLink?: LinkField;

            /**
            * Represents the Text field (f3deb478-90d3-4673-90f9-b2b5d691050e).
            */
            PromoText?: Field<string>;

            /**
            * Represents the Text 2 field (1af0a4b6-0c7e-4285-8c8e-7b0a22208890).
            */
            PromoText2?: Field<string>;

            /**
            * Represents the Text 3 field (7ef147f6-ba69-4d0b-b167-b815a2eeda96).
            */
            PromoText3?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Services Cards
    */
    export type ServicesCardsJson =  {
        
            /**
            * Represents the __Standard Werte field (93ca6686-d483-44cd-b445-e002e80de82e).
            */
            PromoIcon?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Bild 2 field (4b5e4643-fe58-431b-9d2b-0ee738aaaf1c).
            */
            PromoIcon2?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Link field (538c5149-6df9-46c1-84b7-02287a7a283a).
            */
            PromoLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text field (f3deb478-90d3-4673-90f9-b2b5d691050e).
            */
            PromoText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 2 field (1af0a4b6-0c7e-4285-8c8e-7b0a22208890).
            */
            PromoText2?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 3 field (7ef147f6-ba69-4d0b-b167-b815a2eeda96).
            */
            PromoText3?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Parthxmc.ServicesCards {

    /**
    * Represents the template /sitecore/templates/Project/developers/Parth-xmc/Services Cards/Services Cards
    */
    export type ServicesCards = .Page &  {
        fields?: { 
            /**
            * Represents the Services field (832a779d-3920-443f-b435-a1035254d2d7).
            */
            Services?: Item[];
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Parth-xmc/Services Cards/Services Cards
    */
    export type ServicesCardsJson = .PageJson &  {
        
            /**
            * Represents the Services field (832a779d-3920-443f-b435-a1035254d2d7).
            */
            Services?: {
                jsonValue: Item[]
            };


    }
}
export namespace Services {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Services Cards Folder
    */
    export type ServicesCardsFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Services Cards Folder
    */
    export type ServicesCardsFolderJson =  {
        

    }
}
export namespace Services.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Rendering Parameters/Services Cards Parameters
    */
    export type ServicesCardsParameters =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Rendering Parameters/Services Cards Parameters
    */
    export type ServicesCardsParametersJson =  {
        

    }
}
export namespace Parthxmc.ServicesDetails {

    /**
    * Represents the template /sitecore/templates/Project/developers/Parth-xmc/Services Details/Services Details
    */
    export type ServicesDetails = .Page &  {
        fields?: { 
            /**
            * Represents the Description field (9ecd6b68-11f4-42ee-afae-e16882161e0e).
            */
            Description?: Field<string>;

            /**
            * Represents the Image field (d04fb895-3226-4449-850b-fab0d9cee3b7).
            */
            Image?: ImageField;

            /**
            * Represents the TitleName field (2b667b31-03e6-42e3-91ff-912eedf5a608).
            */
            TitleName?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Parth-xmc/Services Details/Services Details
    */
    export type ServicesDetailsJson = .PageJson &  {
        
            /**
            * Represents the Description field (9ecd6b68-11f4-42ee-afae-e16882161e0e).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (d04fb895-3226-4449-850b-fab0d9cee3b7).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the TitleName field (2b667b31-03e6-42e3-91ff-912eedf5a608).
            */
            TitleName?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Parthxmc.ServicesOverview {

    /**
    * Represents the template /sitecore/templates/Project/developers/Parth-xmc/Services Overview/Services Overview
    */
    export type ServicesOverview = .Page &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Parth-xmc/Services Overview/Services Overview
    */
    export type ServicesOverviewJson = .PageJson &  {
        

    }
}
export namespace Sample.Project.developers {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services Teaser
    */
    export type ServicesTeaser =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services Teaser
    */
    export type ServicesTeaserJson =  {
        

    }
}
export namespace Services {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Services Teaser
    */
    export type ServicesTeaser =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Services Teaser
    */
    export type ServicesTeaserJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Services Teaser Folder
    */
    export type ServicesTeaserFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Services Teaser Folder
    */
    export type ServicesTeaserFolderJson =  {
        

    }
}
export namespace Services.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Rendering Parameters/Services Teaser Parameters
    */
    export type ServicesTeaserParameters =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Rendering Parameters/Services Teaser Parameters
    */
    export type ServicesTeaserParametersJson =  {
        

    }
}
export namespace Services {

    /**
    * Represents the template /sitecore/templates/Project/developers/Services/Services Teaser_2
    */
    export type ServicesTeaser2 =  {
        fields?: { 
            /**
            * Represents the __Standard Werte field (f811e011-3534-4ba1-bed8-7a41b4d9011e).
            */
            PromoIcon?: ImageField;

            /**
            * Represents the Bild 2 field (f4093fc0-c549-41f6-bd66-4b67fa1dbdf4).
            */
            PromoIcon2?: ImageField;

            /**
            * Represents the Link field (120f4f69-f20a-432c-be34-35a5fd587df1).
            */
            PromoLink?: LinkField;

            /**
            * Represents the Text field (cd66ac47-0d6e-4f8f-9569-cb88606cbea1).
            */
            PromoText?: Field<string>;

            /**
            * Represents the Text 2 field (aa73f10c-0243-425f-955f-c57d2776b56c).
            */
            PromoText2?: Field<string>;

            /**
            * Represents the Text 3 field (07b162f7-057f-4866-a4eb-dc6bcbb6e98f).
            */
            PromoText3?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Services/Services Teaser_2
    */
    export type ServicesTeaser2Json =  {
        
            /**
            * Represents the __Standard Werte field (f811e011-3534-4ba1-bed8-7a41b4d9011e).
            */
            PromoIcon?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Bild 2 field (f4093fc0-c549-41f6-bd66-4b67fa1dbdf4).
            */
            PromoIcon2?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Link field (120f4f69-f20a-432c-be34-35a5fd587df1).
            */
            PromoLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text field (cd66ac47-0d6e-4f8f-9569-cb88606cbea1).
            */
            PromoText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 2 field (aa73f10c-0243-425f-955f-c57d2776b56c).
            */
            PromoText2?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 3 field (07b162f7-057f-4866-a4eb-dc6bcbb6e98f).
            */
            PromoText3?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Parthxmc.TextAndTitleTamplate {

    /**
    * Represents the template /sitecore/templates/Project/developers/Parth-xmc/TextAndTitle Tamplate/TextAndTitle
    */
    export type TextAndTitle =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Parth-xmc/TextAndTitle Tamplate/TextAndTitle
    */
    export type TextAndTitleJson =  {
        

    }
}
export namespace Parthxmc.TextAndTitle {

    /**
    * Represents the template /sitecore/templates/Project/developers/Parth-xmc/TextAndTitle/TextAndTitle
    */
    export type TextAndTitle =  {
        fields?: { 
            /**
            * Represents the Description field (f3efeb96-afd4-4d7e-a8b7-0244fce893bd).
            */
            Description?: Field<string>;

            /**
            * Represents the Image field (4ae7e101-d2f7-4c5d-8962-06fb495df40d).
            */
            Image?: ImageField;

            /**
            * Represents the Link field (b4d08715-a464-4ae7-a194-b47feb926c0b).
            */
            Link?: LinkField;

            /**
            * Represents the Title field (75f32288-5dee-4e4c-aaec-95a8402e0d28).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/Parth-xmc/TextAndTitle/TextAndTitle
    */
    export type TextAndTitleJson =  {
        
            /**
            * Represents the Description field (f3efeb96-afd4-4d7e-a8b7-0244fce893bd).
            */
            Description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (4ae7e101-d2f7-4c5d-8962-06fb495df40d).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Link field (b4d08715-a464-4ae7-a194-b47feb926c0b).
            */
            Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Title field (75f32288-5dee-4e4c-aaec-95a8402e0d28).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Sample.Project.developers {

    /**
    * Represents the template /sitecore/templates/Project/developers/TokenValues
    */
    export type TokenValues =  {
        fields?: { 
            /**
            * Represents the tokens field (05eef91c-7372-4f43-9698-2d4de53ac8de).
            */
            tokens?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/developers/TokenValues
    */
    export type TokenValuesJson =  {
        
            /**
            * Represents the tokens field (05eef91c-7372-4f43-9698-2d4de53ac8de).
            */
            tokens?: {
                jsonValue: Field<string>
            };


    }
}


